version: "0.1"
services:
  rolebot-rust:
    build: ./
    hostname: rolebot-rust
    container_name: rolebot-rust
    networks:
      - rolebot-net
    ports:
      - "443"
      - "80"
    restart: unless-stopped
    volumes:
      - csvdb:/app/db/
      - .env:/app/.env
      - buildcache:/app/target/release/
    env_file:
      - .env

networks:
  # The presence of these objects is sufficient to define them
  rolebot-net: {}
volumes:
  csvdb: {}
  buildcache: {}
