version: "0.1"
services:
  rolebot-rust:
    build: ./
    hostname: rolebot-rust
    container_name: rolebot-rust
    networks:
      - rolebot-net
    ports:
      - "443"
      - "80"
    restart: unless-stopped

networks:
  # The presence of these objects is sufficient to define them
  rolebot-net: {}

